project:
  type: website
  # pre-render:
    # - scripts/pre_create_papers_file.py
    # - scripts/pre_check_skierg_records.py
    # - scripts/pre_doi_from_rogue_scholar.py
    # - scripts/pre_canonicalise_tags.py
resources:
  - CNAME

website:
  title: "Hunter Glanz"
  description: "Hunter Glanz is an educator and data scientist."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers
        text: Papers
      - href: teaching
        text: Teaching
      - href: media
        text: Media
      - href: posts
        text: The Notebook
      - href: talks
        text: Talks
      - href: https://www.pearson.com/en-us/subject-catalog/p/data-science-for-all/P200000011880/9780135311189
        text: Textbook
  page-footer:
    left: "(c) Hunter Glanz, 2024–. [Disclaimer](disclaimer)"
  twitter-card: true
  open-graph: true
  # google-analytics: "395640625"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center
    include-in-header:
      text: |
        <script type='application/ld+json'>{"@context":"http://www.schema.org","@type":"person","name":"Hunter Glanz","jobTitle":"Data Science Educator","description":"Hunter Glanz is an educator and data scientist.","url":"https://hglanz.github.io/hunter_glanz/","image":"https://hglanz.github.io/hunter_glanz/img/hunter_glanz.jpg","address":{"@type":"PostalAddress","addressLocality":"San Luis Obispo","addressRegion":"CA","postalCode":"93401","addressCountry":"United States"},"alumniOf":[{"@type":"CollegeOrUniversity","name":"Cal Poly, San Luis Obispo","sameAs":"https://en.wikipedia.org/wiki/California_Polytechnic_State_University,_San_Luis_Obispo"},{"@type":"CollegeOrUniversity","name":"Boston University","sameAs":"https://en.wikipedia.org/wiki/Boston_University"}],"worksFor":[{"@type":"Organization","name":"Cal Poly, San Luis Obispo"}],"memberOf":[{"@type":"Organization","name":"American Statistical Association"},{"@type":"Organization","name":"American Mathematical Association of Two-Year Colleges"}]}</script>




