project:
  type: website
  output-dir: docs

website:
  title: "Hunter Glanz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: personal.qmd
        text: Personal
      - href: academic.qmd
        text: Academic
      - href: professional.qmd
        text: Professional
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

